# Generated by Django 3.2 on 2022-08-06 03:51 

from django.db import migrations
from products.models import Product


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
INSERT INTO products_product(name,description,sku,price,image) VALUES ('Paracetamol','Paracetamol (acetaminophen) is a pain reliever and a fever reducer','8HE902',300,'https://www.m-medix.com/2759-large_default/emzor-paracetamol-tablets.jpg');
INSERT INTO products_product(name,description,sku,price,image) VALUES ('Prednisolone','Prednisolone is a corticosteroid (cortisone-like medicine or steroid). It works on the immune system to help relieve swelling, redness, itching, and allergic reactions','8HE809',600,'https://5.imimg.com/data5/RU/SX/JJ/SELLER-109604861/prednisolone-tablet-500x500.jpg');
INSERT INTO products_product(name,description,sku,price,image) VALUES ('Lumefantrine','Lumefantrine is an antimalarial agent used to treat acute uncomplicated malaria.','8HE809',1200,'https://i1.wp.com/nimedhealth.com.ng/wp-content/uploads/2020/09/IMG_20200920_082326-1.jpg?fit=2487%2C1599&ssl=1');
INSERT INTO products_product(name,description,sku,price,image) VALUES ('Coflin','Coflin Is Used To Treat Coughs And Congestion Caused By The Common Cold, Bronchitis, And Other Breathing Illnesses.','8HE809',1200,'https://www.m-medix.com/2677-large_default/dr-meyers-coflin-expectorant-100ml.jpg');
            """
        )
    ]
